language: c

sudo: required

services: docker

env: OCAML_VERSION=4.04 EXTRA_DEPS="oasis alcotest" INSTALL=false

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8.2
    - os: linux
      dist: trusty

before_install:
  - docker pull ryanrhymes/owl:latest
  - docker run -d ryanrhymes/owl /bin/sh -c "make cleanall; wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh; bash -ex .travis-opam.sh"

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update;
      rm '/usr/local/include/c++';
      brew install homebrew/science/openblas;
    fi
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh

script: bash -ex .travis-opam.sh
